/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class ArticleShop implements java.io.Serializable {

	private static final long serialVersionUID = -88025892;

	private java.lang.Long articleId;
	private java.lang.Long shopId;

	public java.lang.Long getArticleId() {
		return this.articleId;
	}

	public void setArticleId(java.lang.Long articleId) {
		this.articleId = articleId;
	}

	public java.lang.Long getShopId() {
		return this.shopId;
	}

	public void setShopId(java.lang.Long shopId) {
		this.shopId = shopId;
	}
}
