/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Shop implements java.io.Serializable {

	private static final long serialVersionUID = 1068046952;

	private java.lang.Long   shopId;
	private java.lang.String name;
	private java.lang.String address;
	private java.lang.Double latitud;
	private java.lang.Double longitud;
	private java.lang.String schedule;
	private java.lang.String email;

	public java.lang.Long getShopId() {
		return this.shopId;
	}

	public void setShopId(java.lang.Long shopId) {
		this.shopId = shopId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(java.lang.Double latitud) {
		this.latitud = latitud;
	}

	public java.lang.Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(java.lang.Double longitud) {
		this.longitud = longitud;
	}

	public java.lang.String getSchedule() {
		return this.schedule;
	}

	public void setSchedule(java.lang.String schedule) {
		this.schedule = schedule;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}
}
