/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 240301167;

	private java.lang.Long                                userId;
	private java.lang.String                              userName;
	private java.lang.String                              userEmail;
	private java.sql.Date                                 userBirthday;
	private com.personalshopper.jooq.enums.UserUserGender userGender;
	private java.lang.String                              userSizeShirt;
	private java.lang.String                              userSizePants;
	private java.lang.String                              userSizeShoes;

	public java.lang.Long getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Long userId) {
		this.userId = userId;
	}

	public java.lang.String getUserName() {
		return this.userName;
	}

	public void setUserName(java.lang.String userName) {
		this.userName = userName;
	}

	public java.lang.String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(java.lang.String userEmail) {
		this.userEmail = userEmail;
	}

	public java.sql.Date getUserBirthday() {
		return this.userBirthday;
	}

	public void setUserBirthday(java.sql.Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	public com.personalshopper.jooq.enums.UserUserGender getUserGender() {
		return this.userGender;
	}

	public void setUserGender(com.personalshopper.jooq.enums.UserUserGender userGender) {
		this.userGender = userGender;
	}

	public java.lang.String getUserSizeShirt() {
		return this.userSizeShirt;
	}

	public void setUserSizeShirt(java.lang.String userSizeShirt) {
		this.userSizeShirt = userSizeShirt;
	}

	public java.lang.String getUserSizePants() {
		return this.userSizePants;
	}

	public void setUserSizePants(java.lang.String userSizePants) {
		this.userSizePants = userSizePants;
	}

	public java.lang.String getUserSizeShoes() {
		return this.userSizeShoes;
	}

	public void setUserSizeShoes(java.lang.String userSizeShoes) {
		this.userSizeShoes = userSizeShoes;
	}
}
