/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class UserArticle implements java.io.Serializable {

	private static final long serialVersionUID = 114349778;

	private java.lang.Long     userId;
	private java.lang.Long     articleId;
	private java.sql.Timestamp visitTime;

	public java.lang.Long getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Long userId) {
		this.userId = userId;
	}

	public java.lang.Long getArticleId() {
		return this.articleId;
	}

	public void setArticleId(java.lang.Long articleId) {
		this.articleId = articleId;
	}

	public java.sql.Timestamp getVisitTime() {
		return this.visitTime;
	}

	public void setVisitTime(java.sql.Timestamp visitTime) {
		this.visitTime = visitTime;
	}
}
