/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class ArticleShopRecord extends org.jooq.impl.UpdatableRecordImpl<com.personalshopper.jooq.tables.records.ArticleShopRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -1503082822;

	/**
	 * Setter for <code>personal_shopper.article_shop.article_id</code>. 
	 */
	public void setArticleId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>personal_shopper.article_shop.article_id</code>. 
	 */
	public java.lang.Long getArticleId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>personal_shopper.article_shop.shop_id</code>. 
	 */
	public void setShopId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>personal_shopper.article_shop.shop_id</code>. 
	 */
	public java.lang.Long getShopId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP.ARTICLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP.SHOP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getArticleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getShopId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ArticleShopRecord
	 */
	public ArticleShopRecord() {
		super(com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP);
	}
}
