/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class ShopRecord extends org.jooq.impl.UpdatableRecordImpl<com.personalshopper.jooq.tables.records.ShopRecord> implements org.jooq.Record7<java.lang.Long, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 522883492;

	/**
	 * Setter for <code>personal_shopper.shop.shop_id</code>. 
	 */
	public void setShopId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.shop_id</code>. 
	 */
	public java.lang.Long getShopId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>personal_shopper.shop.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>personal_shopper.shop.address</code>. 
	 */
	public void setAddress(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.address</code>. 
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>personal_shopper.shop.latitud</code>. 
	 */
	public void setLatitud(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.latitud</code>. 
	 */
	public java.lang.Double getLatitud() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>personal_shopper.shop.longitud</code>. 
	 */
	public void setLongitud(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.longitud</code>. 
	 */
	public java.lang.Double getLongitud() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>personal_shopper.shop.schedule</code>. 
	 */
	public void setSchedule(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.schedule</code>. 
	 */
	public java.lang.String getSchedule() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>personal_shopper.shop.email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>personal_shopper.shop.email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.personalshopper.jooq.tables.Shop.SHOP.SHOP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.personalshopper.jooq.tables.Shop.SHOP.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.personalshopper.jooq.tables.Shop.SHOP.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return com.personalshopper.jooq.tables.Shop.SHOP.LATITUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return com.personalshopper.jooq.tables.Shop.SHOP.LONGITUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.personalshopper.jooq.tables.Shop.SHOP.SCHEDULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.personalshopper.jooq.tables.Shop.SHOP.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getShopId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getLatitud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getLongitud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSchedule();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getEmail();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ShopRecord
	 */
	public ShopRecord() {
		super(com.personalshopper.jooq.tables.Shop.SHOP);
	}
}
