/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class UserArticleRecord extends org.jooq.impl.TableRecordImpl<com.personalshopper.jooq.tables.records.UserArticleRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -1871738165;

	/**
	 * Setter for <code>personal_shopper.user_article.user_id</code>. 
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>personal_shopper.user_article.user_id</code>. 
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>personal_shopper.user_article.article_id</code>. 
	 */
	public void setArticleId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>personal_shopper.user_article.article_id</code>. 
	 */
	public java.lang.Long getArticleId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.personalshopper.jooq.tables.UserArticle.USER_ARTICLE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.personalshopper.jooq.tables.UserArticle.USER_ARTICLE.ARTICLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getArticleId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserArticleRecord
	 */
	public UserArticleRecord() {
		super(com.personalshopper.jooq.tables.UserArticle.USER_ARTICLE);
	}
}
