/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>personal_shopper</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.personalshopper.jooq.tables.records.ArticlesRecord, java.lang.Long> IDENTITY_ARTICLES = Identities0.IDENTITY_ARTICLES;
	public static final org.jooq.Identity<com.personalshopper.jooq.tables.records.ShopsRecord, java.lang.Long> IDENTITY_SHOPS = Identities0.IDENTITY_SHOPS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticlesRecord> KEY_ARTICLES_PRIMARY = UniqueKeys0.KEY_ARTICLES_PRIMARY;
	public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticlesRecord> KEY_ARTICLES_ARTICLE_ID = UniqueKeys0.KEY_ARTICLES_ARTICLE_ID;
	public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleShopRecord> KEY_ARTICLE_SHOP_PRIMARY = UniqueKeys0.KEY_ARTICLE_SHOP_PRIMARY;
	public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopsRecord> KEY_SHOPS_PRIMARY = UniqueKeys0.KEY_SHOPS_PRIMARY;
	public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopsRecord> KEY_SHOPS_SHOP_ID = UniqueKeys0.KEY_SHOPS_SHOP_ID;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.ArticleShopRecord, com.personalshopper.jooq.tables.records.ArticlesRecord> ARTICLE_SHOP_IBFK_1 = ForeignKeys0.ARTICLE_SHOP_IBFK_1;
	public static final org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.ArticleShopRecord, com.personalshopper.jooq.tables.records.ShopsRecord> ARTICLE_SHOP_IBFK_2 = ForeignKeys0.ARTICLE_SHOP_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.personalshopper.jooq.tables.records.ArticlesRecord, java.lang.Long> IDENTITY_ARTICLES = createIdentity(com.personalshopper.jooq.tables.Articles.ARTICLES, com.personalshopper.jooq.tables.Articles.ARTICLES.ARTICLE_ID);
		public static org.jooq.Identity<com.personalshopper.jooq.tables.records.ShopsRecord, java.lang.Long> IDENTITY_SHOPS = createIdentity(com.personalshopper.jooq.tables.Shops.SHOPS, com.personalshopper.jooq.tables.Shops.SHOPS.SHOP_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticlesRecord> KEY_ARTICLES_PRIMARY = createUniqueKey(com.personalshopper.jooq.tables.Articles.ARTICLES, com.personalshopper.jooq.tables.Articles.ARTICLES.ARTICLE_ID);
		public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticlesRecord> KEY_ARTICLES_ARTICLE_ID = createUniqueKey(com.personalshopper.jooq.tables.Articles.ARTICLES, com.personalshopper.jooq.tables.Articles.ARTICLES.ARTICLE_ID);
		public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleShopRecord> KEY_ARTICLE_SHOP_PRIMARY = createUniqueKey(com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP, com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP.ARTICLE_ID);
		public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopsRecord> KEY_SHOPS_PRIMARY = createUniqueKey(com.personalshopper.jooq.tables.Shops.SHOPS, com.personalshopper.jooq.tables.Shops.SHOPS.SHOP_ID);
		public static final org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopsRecord> KEY_SHOPS_SHOP_ID = createUniqueKey(com.personalshopper.jooq.tables.Shops.SHOPS, com.personalshopper.jooq.tables.Shops.SHOPS.SHOP_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.ArticleShopRecord, com.personalshopper.jooq.tables.records.ArticlesRecord> ARTICLE_SHOP_IBFK_1 = createForeignKey(com.personalshopper.jooq.Keys.KEY_ARTICLES_PRIMARY, com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP, com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP.ARTICLE_ID);
		public static final org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.ArticleShopRecord, com.personalshopper.jooq.tables.records.ShopsRecord> ARTICLE_SHOP_IBFK_2 = createForeignKey(com.personalshopper.jooq.Keys.KEY_SHOPS_PRIMARY, com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP, com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP.SHOP_ID);
	}
}
