/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class PersonalShopper extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -353064754;

	/**
	 * The singleton instance of <code>personal_shopper</code>
	 */
	public static final PersonalShopper PERSONAL_SHOPPER = new PersonalShopper();

	/**
	 * No further instances allowed
	 */
	private PersonalShopper() {
		super("personal_shopper");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.personalshopper.jooq.tables.Article.ARTICLE,
			com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP,
			com.personalshopper.jooq.tables.Shop.SHOP,
			com.personalshopper.jooq.tables.User.USER,
			com.personalshopper.jooq.tables.UserArticle.USER_ARTICLE);
	}
}
