/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in personal_shopper
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Tables {

	/**
	 * The table personal_shopper.article
	 */
	public static final com.personalshopper.jooq.tables.Article ARTICLE = com.personalshopper.jooq.tables.Article.ARTICLE;

	/**
	 * The table personal_shopper.article_shop
	 */
	public static final com.personalshopper.jooq.tables.ArticleShop ARTICLE_SHOP = com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP;

	/**
	 * The table personal_shopper.shop
	 */
	public static final com.personalshopper.jooq.tables.Shop SHOP = com.personalshopper.jooq.tables.Shop.SHOP;

	/**
	 * The table personal_shopper.user
	 */
	public static final com.personalshopper.jooq.tables.User USER = com.personalshopper.jooq.tables.User.USER;

	/**
	 * The table personal_shopper.user_article
	 */
	public static final com.personalshopper.jooq.tables.UserArticle USER_ARTICLE = com.personalshopper.jooq.tables.UserArticle.USER_ARTICLE;
}
