/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class ArticleShop extends org.jooq.impl.TableImpl<com.personalshopper.jooq.tables.records.ArticleShopRecord> {

	private static final long serialVersionUID = 937704587;

	/**
	 * The singleton instance of <code>personal_shopper.article_shop</code>
	 */
	public static final com.personalshopper.jooq.tables.ArticleShop ARTICLE_SHOP = new com.personalshopper.jooq.tables.ArticleShop();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.personalshopper.jooq.tables.records.ArticleShopRecord> getRecordType() {
		return com.personalshopper.jooq.tables.records.ArticleShopRecord.class;
	}

	/**
	 * The column <code>personal_shopper.article_shop.article_id</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleShopRecord, java.lang.Long> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>personal_shopper.article_shop.shop_id</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleShopRecord, java.lang.Long> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * Create a <code>personal_shopper.article_shop</code> table reference
	 */
	public ArticleShop() {
		super("article_shop", com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER);
	}

	/**
	 * Create an aliased <code>personal_shopper.article_shop</code> table reference
	 */
	public ArticleShop(java.lang.String alias) {
		super(alias, com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER, com.personalshopper.jooq.tables.ArticleShop.ARTICLE_SHOP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleShopRecord> getPrimaryKey() {
		return com.personalshopper.jooq.Keys.KEY_ARTICLE_SHOP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleShopRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleShopRecord>>asList(com.personalshopper.jooq.Keys.KEY_ARTICLE_SHOP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.ArticleShopRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.ArticleShopRecord, ?>>asList(com.personalshopper.jooq.Keys.ARTICLE_SHOP_IBFK_1, com.personalshopper.jooq.Keys.ARTICLE_SHOP_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.personalshopper.jooq.tables.ArticleShop as(java.lang.String alias) {
		return new com.personalshopper.jooq.tables.ArticleShop(alias);
	}
}
