/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Article extends org.jooq.impl.TableImpl<com.personalshopper.jooq.tables.records.ArticleRecord> {

	private static final long serialVersionUID = -1892973978;

	/**
	 * The singleton instance of <code>personal_shopper.article</code>
	 */
	public static final com.personalshopper.jooq.tables.Article ARTICLE = new com.personalshopper.jooq.tables.Article();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.personalshopper.jooq.tables.records.ArticleRecord> getRecordType() {
		return com.personalshopper.jooq.tables.records.ArticleRecord.class;
	}

	/**
	 * The column <code>personal_shopper.article.article_id</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.Long> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>personal_shopper.article.type</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, com.personalshopper.jooq.enums.ArticleType> TYPE = createField("type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.personalshopper.jooq.enums.ArticleType.class), this);

	/**
	 * The column <code>personal_shopper.article.model</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.String> MODEL = createField("model", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.article.brand</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.String> BRAND = createField("brand", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.article.size</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.Object> SIZE = createField("size", org.jooq.impl.DefaultDataType.getDefaultDataType("tinytext"), this);

	/**
	 * The column <code>personal_shopper.article.colour</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.String> COLOUR = createField("colour", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.article.price</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.Double> PRICE = createField("price", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>personal_shopper.article.picture</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.article.date</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ArticleRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>personal_shopper.article</code> table reference
	 */
	public Article() {
		super("article", com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER);
	}

	/**
	 * Create an aliased <code>personal_shopper.article</code> table reference
	 */
	public Article(java.lang.String alias) {
		super(alias, com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER, com.personalshopper.jooq.tables.Article.ARTICLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.personalshopper.jooq.tables.records.ArticleRecord, java.lang.Long> getIdentity() {
		return com.personalshopper.jooq.Keys.IDENTITY_ARTICLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleRecord> getPrimaryKey() {
		return com.personalshopper.jooq.Keys.KEY_ARTICLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ArticleRecord>>asList(com.personalshopper.jooq.Keys.KEY_ARTICLE_PRIMARY, com.personalshopper.jooq.Keys.KEY_ARTICLE_ARTICLE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.personalshopper.jooq.tables.Article as(java.lang.String alias) {
		return new com.personalshopper.jooq.tables.Article(alias);
	}
}
