/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class Shop extends org.jooq.impl.TableImpl<com.personalshopper.jooq.tables.records.ShopRecord> {

	private static final long serialVersionUID = -1967329704;

	/**
	 * The singleton instance of <code>personal_shopper.shop</code>
	 */
	public static final com.personalshopper.jooq.tables.Shop SHOP = new com.personalshopper.jooq.tables.Shop();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.personalshopper.jooq.tables.records.ShopRecord> getRecordType() {
		return com.personalshopper.jooq.tables.records.ShopRecord.class;
	}

	/**
	 * The column <code>personal_shopper.shop.shop_id</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.Long> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>personal_shopper.shop.name</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.shop.address</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.shop.latitud</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.Double> LATITUD = createField("latitud", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>personal_shopper.shop.longitud</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.Double> LONGITUD = createField("longitud", org.jooq.impl.SQLDataType.FLOAT, this);

	/**
	 * The column <code>personal_shopper.shop.schedule</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.String> SCHEDULE = createField("schedule", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>personal_shopper.shop.email</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * Create a <code>personal_shopper.shop</code> table reference
	 */
	public Shop() {
		super("shop", com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER);
	}

	/**
	 * Create an aliased <code>personal_shopper.shop</code> table reference
	 */
	public Shop(java.lang.String alias) {
		super(alias, com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER, com.personalshopper.jooq.tables.Shop.SHOP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.personalshopper.jooq.tables.records.ShopRecord, java.lang.Long> getIdentity() {
		return com.personalshopper.jooq.Keys.IDENTITY_SHOP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopRecord> getPrimaryKey() {
		return com.personalshopper.jooq.Keys.KEY_SHOP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.personalshopper.jooq.tables.records.ShopRecord>>asList(com.personalshopper.jooq.Keys.KEY_SHOP_PRIMARY, com.personalshopper.jooq.Keys.KEY_SHOP_SHOP_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.personalshopper.jooq.tables.Shop as(java.lang.String alias) {
		return new com.personalshopper.jooq.tables.Shop(alias);
	}
}
