/**
 * This class is generated by jOOQ
 */
package com.personalshopper.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked" })
public class UserArticle extends org.jooq.impl.TableImpl<com.personalshopper.jooq.tables.records.UserArticleRecord> {

	private static final long serialVersionUID = 1997040690;

	/**
	 * The singleton instance of <code>personal_shopper.user_article</code>
	 */
	public static final com.personalshopper.jooq.tables.UserArticle USER_ARTICLE = new com.personalshopper.jooq.tables.UserArticle();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.personalshopper.jooq.tables.records.UserArticleRecord> getRecordType() {
		return com.personalshopper.jooq.tables.records.UserArticleRecord.class;
	}

	/**
	 * The column <code>personal_shopper.user_article.user_id</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.UserArticleRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>personal_shopper.user_article.article_id</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.UserArticleRecord, java.lang.Long> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>personal_shopper.user_article.visit_time</code>. 
	 */
	public final org.jooq.TableField<com.personalshopper.jooq.tables.records.UserArticleRecord, java.sql.Timestamp> VISIT_TIME = createField("visit_time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>personal_shopper.user_article</code> table reference
	 */
	public UserArticle() {
		super("user_article", com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER);
	}

	/**
	 * Create an aliased <code>personal_shopper.user_article</code> table reference
	 */
	public UserArticle(java.lang.String alias) {
		super(alias, com.personalshopper.jooq.PersonalShopper.PERSONAL_SHOPPER, com.personalshopper.jooq.tables.UserArticle.USER_ARTICLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.UserArticleRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.personalshopper.jooq.tables.records.UserArticleRecord, ?>>asList(com.personalshopper.jooq.Keys.USER_ARTICLE_IBFK_1, com.personalshopper.jooq.Keys.USER_ARTICLE_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.personalshopper.jooq.tables.UserArticle as(java.lang.String alias) {
		return new com.personalshopper.jooq.tables.UserArticle(alias);
	}
}
