/**
 * This class is generated by jOOQ
 */
package com.personalshopper.data;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in personal_shopper
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "3.0.1"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table personal_shopper.articles
	 */
	public static final com.personalshopper.data.tables.Articles ARTICLES = com.personalshopper.data.tables.Articles.ARTICLES;

	/**
	 * The table personal_shopper.article_shop
	 */
	public static final com.personalshopper.data.tables.ArticleShop ARTICLE_SHOP = com.personalshopper.data.tables.ArticleShop.ARTICLE_SHOP;

	/**
	 * The table personal_shopper.shops
	 */
	public static final com.personalshopper.data.tables.Shops SHOPS = com.personalshopper.data.tables.Shops.SHOPS;
}
